<a href="https://colab.research.google.com/github/AbhishekShah272002/Deep-Learning-and-NLP/blob/main/NLP_Based_Sentiment_Analysis_of_E_Commerce_Customer_Feedback.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import re
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [ ]:
df = pd.read_csv(
    "ecommerce_customer_feedback.txt",
    header=None,
    names=["Customer_Feedback"],
)
df.head()

                                   Customer_Feedback
0  The packaging was damaged and the product was ...
1  I placed the order through the mobile applicat...
2  I used the online payment option for this orde...
3  The checkout page kept showing an error during...
4  The seller cancelled my order without giving a...

In [ ]:
print("Dataset Shape:", df.shape)

print("\nDataset Information:")
df.info()

print("\nMissing Values:")
print(df.isnull().sum())

Dataset Shape: (300, 1)

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_Feedback  300 non-null    object
dtypes: object(1)
memory usage: 2.5+ KB

Missing Values:
Customer_Feedback    0
dtype: int64

In [ ]:
df["Cleaned_Feedback"] = df["Customer_Feedback"].str.lower()

df[["Customer_Feedback", "Cleaned_Feedback"]].head()

,Customer_Feedback,Cleaned_Feedback
0,the packaging was damaged and the product was ...,the packaging was damaged and the product was ...
1,i placed the order through the mobile applicat...,i placed the order through the mobile applicat...
2,i used the online payment option for this orde...,i used the online payment option for this orde...
3,the checkout page kept showing an error during...,the checkout page kept showing an error during...
4,the seller cancelled my order without giving a...,the seller cancelled my order without giving a...

In [ ]:
df["Cleaned_Feedback"] = df["Cleaned_Feedback"].apply(
    lambda text: re.sub(r'[^a-z\s]', '', text)
)

df[["Customer_Feedback", "Cleaned_Feedback"]].head()

,Customer_Feedback,Cleaned_Feedback
0,the packaging was damaged and the product was ...,the packaging was damaged and the product was ...
1,i placed the order through the mobile applicat...,i placed the order through the mobile applicat...
2,i used the online payment option for this orde...,i used the online payment option for this orde...
3,the checkout page kept showing an error during...,the checkout page kept showing an error during...
4,the seller cancelled my order without giving a...,the seller cancelled my order without giving a...

In [13]:
nltk.download("punkt")
nltk.download("punkt_tab")

df["Tokens"] = df["Cleaned_Feedback"].apply(word_tokenize)

df[["Cleaned_Feedback", "Tokens"]].head()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

,Cleaned_Feedback,Tokens
0,the packaging was damaged and the product was ...,"[the, packaging, was, damaged, and, the, produ..."
1,i placed the order through the mobile applicat...,"[i, placed, the, order, through, the, mobile, ..."
2,i used the online payment option for this orde...,"[i, used, the, online, payment, option, for, t..."
3,the checkout page kept showing an error during...,"[the, checkout, page, kept, showing, an, error..."
4,the seller cancelled my order without giving a...,"[the, seller, cancelled, my, order, without, g..."

In [17]:
nltk.download("stopwords")

stop_words = set(stopwords.words("english"))

df["Tokens_No_Stopwords"] = df["Tokens"].apply(
  lambda words: [word for word in words if word not in stop_words]
)

df[["Tokens", "Tokens_No_Stopwords"]].head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

,Tokens,Tokens_No_Stopwords
0,"[the, packaging, was, damaged, and, the, produ...","[packaging, damaged, product, broken, feedback..."
1,"[i, placed, the, order, through, the, mobile, ...","[placed, order, mobile, application, overall, ..."
2,"[i, used, the, online, payment, option, for, t...","[used, online, payment, option, order, feedbac..."
3,"[the, checkout, page, kept, showing, an, error...","[checkout, page, kept, showing, error, payment..."
4,"[the, seller, cancelled, my, order, without, g...","[seller, cancelled, order, without, giving, re..."